import { Project, ProjectPriority, ProjectStatus } from './types';

export const STATUS_COLORS: { [key in ProjectStatus]: string } = {
  [ProjectStatus.Completed]: 'bg-green-500',
  [ProjectStatus.InProgress]: 'bg-blue-500',
  [ProjectStatus.NotStarted]: 'bg-gray-500',
  [ProjectStatus.OnHold]: 'bg-yellow-500',
};

export const PRIORITY_COLORS: { [key in ProjectPriority]: string } = {
    [ProjectPriority.Low]: 'bg-blue-600',
    [ProjectPriority.Medium]: 'bg-yellow-600',
    [ProjectPriority.High]: 'bg-orange-600',
    [ProjectPriority.Critical]: 'bg-red-600',
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'ProjectFlow UI Development',
    description: 'Developing the core user interface components and layouts for the ProjectFlow application using React and Tailwind CSS.',
    category: 'Web Development',
    priority: ProjectPriority.High,
    startDate: '2024-07-01',
    endDate: '2024-08-15',
    status: ProjectStatus.InProgress,
    imageUrl: 'https://picsum.photos/seed/project1/1200/400',
    projectLink: 'https://github.com/example/projectflow',
    subtasks: [
      { id: '1-1', projectId: '1', description: 'Setup React boilerplate', isCompleted: true },
      { id: '1-2', projectId: '1', description: 'Design component library', isCompleted: true },
      { id: '1-3', projectId: '1', description: 'Implement Dashboard view', isCompleted: true },
      { id: '1-4', projectId: '1', description: 'Implement Timeline view', isCompleted: false },
      { id: '1-5', projectId: '1', description: 'Implement Project Details Modal', isCompleted: false },
    ],
    isArchived: false,
  },
  {
    id: '2',
    title: 'API Backend for ProjectFlow',
    description: 'Building a robust Node.js and Express.js backend with a PostgreSQL database to manage project and task data.',
    category: 'Infrastructure',
    priority: ProjectPriority.Critical,
    startDate: '2024-07-10',
    endDate: '2024-09-01',
    status: ProjectStatus.InProgress,
    imageUrl: 'https://picsum.photos/seed/project2/1200/400',
    projectLink: 'https://github.com/example/projectflow-api',
    subtasks: [
        { id: '2-1', projectId: '2', description: 'Design database schema', isCompleted: true },
        { id: '2-2', projectId: '2', description: 'Setup Node/Express server', isCompleted: true },
        { id: '2-3', projectId: '2', description: 'Implement Project CRUD endpoints', isCompleted: false },
        { id: '2-4', projectId: '2', description: 'Implement Subtask CRUD endpoints', isCompleted: false },
        { id: '2-5', projectId: '2', description: 'Add user authentication', isCompleted: false },
    ],
    isArchived: false,
  },
  {
    id: '3',
    title: 'Q3 Marketing Campaign',
    description: 'Plan and execute the marketing campaign for the third quarter, focusing on new feature launches and user acquisition.',
    category: 'Marketing',
    priority: ProjectPriority.Medium,
    startDate: '2024-07-20',
    endDate: '2024-09-30',
    status: ProjectStatus.NotStarted,
    imageUrl: 'https://picsum.photos/seed/project3/1200/400',
    projectLink: 'https://example.com/marketing-brief',
    subtasks: [
        { id: '3-1', projectId: '3', description: 'Finalize campaign messaging', isCompleted: false },
        { id: '3-2', projectId: '3', description: 'Create ad creatives', isCompleted: false },
        { id: '3-3', projectId: '3', description: 'Launch social media campaign', isCompleted: false },
    ],
    isArchived: false,
  },
  {
    id: '4',
    title: 'Data Science Model Training',
    description: 'Train a new machine learning model to predict project completion times based on historical data.',
    category: 'Data Science',
    priority: ProjectPriority.Medium,
    startDate: '2024-06-15',
    endDate: '2024-07-25',
    status: ProjectStatus.Completed,
    imageUrl: 'https://picsum.photos/seed/project4/1200/400',
    projectLink: '',
    subtasks: [
        { id: '4-1', projectId: '4', description: 'Gather and clean data', isCompleted: true },
        { id: '4-2', projectId: '4', description: 'Feature engineering', isCompleted: true },
        { id: '4-3', projectId: '4', description: 'Train and validate model', isCompleted: true },
        { id: '4-4', projectId: '4', description: 'Deploy model to staging', isCompleted: true },
    ],
    isArchived: false,
  },
   {
    id: '5',
    title: 'HR Onboarding Process Revamp',
    description: 'Overhaul the new hire onboarding process to improve efficiency and employee experience.',
    category: 'Human Resources',
    priority: ProjectPriority.Low,
    startDate: '2024-08-01',
    endDate: '2024-09-15',
    status: ProjectStatus.NotStarted,
    imageUrl: 'https://picsum.photos/seed/project5/1200/400',
    projectLink: '',
    subtasks: [
        { id: '5-1', projectId: '5', description: 'Survey new hires for feedback', isCompleted: false },
        { id: '5-2', projectId: '5', description: 'Redesign onboarding documents', isCompleted: false },
    ],
    isArchived: false,
  },
  {
    id: '6',
    title: 'Customer Support System Upgrade',
    description: 'Migrate the existing customer support platform to a new, more scalable solution.',
    category: 'Infrastructure',
    priority: ProjectPriority.High,
    startDate: '2024-06-20',
    endDate: '2024-08-05',
    status: ProjectStatus.OnHold,
    imageUrl: 'https://picsum.photos/seed/project6/1200/400',
    projectLink: '',
    subtasks: [
        { id: '6-1', projectId: '6', description: 'Evaluate new platform vendors', isCompleted: true },
        { id: '6-2', projectId: '6', description: 'Plan data migration strategy', isCompleted: true },
        { id: '6-3', projectId: '6', description: 'Vendor contract negotiations on hold', isCompleted: false },
    ],
    isArchived: false,
  },
];